# Configuration for molecular property counting questions
system_prompt: "You are a chemist. Place answers in <answer> tags. Do not explain. "

question_set: molecular_properties

questions:
  - id: sorted_rings
    user_template: "What are the atom map numbers of the rings in the molecule {kekulized_smiles_atom_map} in JSON format? The list of atom map numbers for each ring are sorted. The list of rings is sorted by the max atom map number and then the min atom map number of each ring.\n"
    assistant_template: "The rings are <answer>{sorted_rings}</answer>\n"
  - id: longest_chain
    user_template: "What are the atom map numbers of the longest_carbon_chain in the molecule {kekulized_smiles_atom_map} where none of the carbons are in a ring? The answer should be in JSON format and the atom map numbers sorted.\n"
    assistant_template: "The atom map numbers of the longest_carbon_chain are <answer>{longest_chain}</answer>\n"
