# Configuration for molecular property counting questions
system_prompt: "You are a chemist. Place answers in <answer> tags. Do not explain. "

question_set: molecular_properties

questions:
  - id: molecular_formula
    user_template: "What is the molecular formula of the molecule {kekulized_smiles}?\n"
    assistant_template: "The molecular formula is <answer>{molecular_formula}</answer>\n"
  - id: stereo_summary
    user_template: "How many stereocenters and stereo_bonds are in the molecule {kekulized_smiles} in JSON format?\n"
    assistant_template: "The number of stereocenters and stereo_bonds is <answer>{stereo_summary}</answer>\n"
  - id: bond_counts
    user_template: "What is the number of all_bonds (including to hydrogen), double_bonds, and triple_bonds in the Kekulized molecule {kekulized_smiles} in JSON format?\n"
    assistant_template: "The numbers of bonds are <answer>{bond_counts}</answer>\n"
