# Configuration for molecular property counting questions
system_prompt: ""

question_set: molecular_properties

questions:
  - id: carbon_count
    user_template: "How many carbon atoms are in the molecule {smiles}?\n"
    assistant_template: "The number of carbon atoms is: {carbon_count}\n"
  - id: heavy_atom_count
    user_template: "How many heavy (non-hydrogen) atoms are in the molecule {smiles}?\n"
    assistant_template: "The number of heavy (non-hydrogen) atoms is: {heavy_atom_count}\n"
  - id: non_hydrogen_bond_count
    user_template: "How many bonds not to hydrogen are in the molecule {smiles}?\n"
    assistant_template: "The number of bonds not to hydrogen is: {non_hydrogen_bond_count}\n"
  - id: positive_formal_charge_count
    user_template: "How many atoms with positive formal charge are in the molecule {smiles}?\n"
    assistant_template: "The number of atoms with positive formal charge is: {positive_formal_charge_count}\n"
  - id: negative_formal_charge_count
    user_template: "How many atoms with negative formal charge are in the molecule {smiles}?\n"
    assistant_template: "The number of atoms with negative formal charge is: {negative_formal_charge_count}\n"
  - id: nitrogen_count
    user_template: "How many nitrogen atoms are in the molecule {smiles}?\n"
    assistant_template: "The number of nitrogen atoms is: {nitrogen_count}\n"
  - id: oxygen_count
    user_template: "How many oxygen atoms are in the molecule {smiles}?\n"
    assistant_template: "The number of oxygen atoms is: {oxygen_count}\n"
  - id: sulfur_count
    user_template: "How many sulfur atoms are in the molecule {smiles}?\n"
    assistant_template: "The number of sulfur atoms is: {sulfur_count}\n"
  - id: phosphorus_count
    user_template: "How many phosphorus atoms are in the molecule {smiles}?\n"
    assistant_template: "The number of phosphorus atoms is: {phosphorus_count}\n"
  - id: chlorine_count
    user_template: "How many chlorine atoms are in the molecule {smiles}?\n"
    assistant_template: "The number of chlorine atoms is: {chlorine_count}\n"
  - id: fluorine_count
    user_template: "How many fluorine atoms are in the molecule {smiles}?\n"
    assistant_template: "The number of fluorine atoms is: {fluorine_count}\n"
  - id: ring_count
    user_template: "How many rings are in the molecule {smiles} SSSR?\n"
    assistant_template: "The number of rings is: {ring_count}\n"
  - id: aromatic_ring_count
    user_template: "How many aromatic rings are in the molecule {smiles} SSSR?\n"
    assistant_template: "The number of aromatic rings is: {aromatic_ring_count}\n"
  - id: double_bond_count
    user_template: "How many double bonds are in the molecule {smiles}?\n"
    assistant_template: "The number of double bonds is: {double_bond_count}\n"
  - id: triple_bond_count
    user_template: "How many triple bonds are in the molecule {smiles}?\n"
    assistant_template: "The number of triple bonds is: {triple_bond_count}\n"
  - id: stereo_double_bond_count
    user_template: "How many stereo double bonds are in the molecule {smiles}?\n"
    assistant_template: "The number of stereo double bonds is: {stereo_double_bond_count}\n"
  - id: stereocenter_count
    user_template: "How many stereocenters are in the molecule {smiles}?\n"
    assistant_template: "The number of stereocenters is: {stereocenter_count}\n"
  - id: five_membered_ring_count
    user_template: "How many 5-membered rings are in the molecule {smiles}?\n"
    assistant_template: "The number of 5-membered rings is: {five_membered_ring_count}\n"
  - id: aromatic_five_membered_ring_count
    user_template: "How many aromatic 5-membered rings are in the molecule {smiles}?\n"
    assistant_template: "The number of aromatic 5-membered rings is: {aromatic_five_membered_ring_count}\n"
  - id: six_membered_ring_count
    user_template: "How many 6-membered rings are in the molecule {smiles}?\n"
    assistant_template: "The number of 6-membered rings is: {six_membered_ring_count}\n"
  - id: aromatic_six_membered_ring_count
    user_template: "How many aromatic 6-membered rings are in the molecule {smiles}?\n"
    assistant_template: "The number of aromatic 6-membered rings is: {aromatic_six_membered_ring_count}\n"
  - id: fused_ring_count
    user_template: "How many rings in the molecule {smiles} SSSR are fused to at least one other ring?\n"
    assistant_template: "The number of fused rings is: {fused_ring_count}\n"
  - id: aromatic_heterocycle_count
    user_template: "How many aromatic heterocycles are in the molecule {smiles}?\n"
    assistant_template: "The number of aromatic heterocycles is: {aromatic_heterocycle_count}\n"
  - id: aromatic_carbocycle_count
    user_template: "How many aromatic carbocycles are in the molecule {smiles}?\n"
    assistant_template: "The number of aromatic carbocycles is: {aromatic_carbocycle_count}\n"
  - id: aliphatic_heterocycle_count
    user_template: "How many aliphatic heterocycles are in the molecule {smiles}?\n"
    assistant_template: "The number of aliphatic heterocycles is: {aliphatic_heterocycle_count}\n"
  - id: aliphatic_carbocycle_count
    user_template: "How many aliphatic carbocycles are in the molecule {smiles}?\n"
    assistant_template: "The number of aliphatic carbocycles is: {aliphatic_carbocycle_count}\n"
  - id: saturated_heterocycle_count
    user_template: "How many saturated heterocycles are in the molecule {smiles}?\n"
    assistant_template: "The number of saturated heterocycles is: {saturated_heterocycle_count}\n"
  - id: saturated_carbocycle_count
    user_template: "How many saturated carbocycles are in the molecule {smiles}?\n"
    assistant_template: "The number of saturated carbocycles is: {saturated_carbocycle_count}\n"
  - id: hydrogen_count
    user_template: "How many hydrogens (implicit + explicit) are in the molecule {smiles}?\n"
    assistant_template: "The number of hydrogens is: {hydrogen_count}\n"
  - id: longest_chain_length
    user_template: "What is the length of the longest acyclic chain (heavy atoms only, excluding ring bonds) in the molecule {smiles}?\n"
    assistant_template: "The length of the longest acyclic chain is: {longest_chain_length}\n"

